### ISSUE TITLE
SSL error when trying to use Voip

### ISSUE THREAD

**Issue by ipranjal** [nnsnodnb/kalyke#38]
``` 
File "/home/ubuntu/venv/lib/python3.6/site-packages/kalyke/client.py", line 67, in send_message
  result = loop.run_until_complete(self._send_message(registration_id, alert, **kwargs))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
   File "/home/ubuntu/venv/lib/python3.6/site-packages/kalyke/client.py", line 187, in _send_message
    with closing(self._create_connection()) as connection:
   File "/home/ubuntu/venv/lib/python3.6/site-packages/kalyke/client.py", line 280, in _create_connection
ssl.SSLError: [SSL] PEM lib (_ssl.c:3524)
```

I have downloaded voip "pem" file from my developer dashboard and I am using absolute path of pem file , what might be the issue?

**Comment by nnsnodnb** [comment]
Thank you for reporting.

Can you try once without `uvloop`?
I want to know that results.

Best Regards,

**Comment by ipranjal** [comment]
Surprisingly when I tried doing this 
```

    def send_message(self, registration_id: str, alert: Union[Payload, Dict[str, Any]], **kwargs) -> bool:
        #try:
            #return asyncio.run(self._send_message(registration_id, alert, **kwargs))  # type: ignore
        #except AttributeError:
            # try:
            #     loop = asyncio.get_event_loop()
            # except:
            #     loop = asyncio.new_event_loop()
            #     asyncio.set_event_loop(loop)

            # try:
        result = self._send_message(registration_id, alert, **kwargs)
            # finally:
            #     loop.close()
        return result
```

it does not throw an error , is it because I am using with FastAPI ?

**Comment by nnsnodnb** [comment]
I think so maybe...

I plan to change implementation of asynchronous processing in the near future.

**Comment by ipranjal** [comment]
fastapi already uses uvloop I think that's causing some kind of conflict , intrestingly enough if I try to directly send the response sent by client.send_message() function , I end up getting following error

```
ValueError: [TypeError("'coroutine' object is not iterable",), TypeError('vars() argument must have __dict__ attribute',)]
```

**Comment by abhinavsingh** [comment]
Unsure why this was closed, I get a similar error, I am trying this on Macbook currently using a Django shell:

```
>>> asyncio.run(client.send_message(device_token=registration_id, payload=payload, apns_config=config))
Traceback (most recent call last):
  File "/Users/abhinavsingh/.pyenv/versions/3.10.6/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/Users/abhinavsingh/.pyenv/versions/3.10.6/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/abhinavsingh/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/abhinavsingh/Dev/projects/.venv/lib/python3.10/site-packages/kalyke/clients/__init__.py", line 28, in send_message
    async with self._init_client(apns_config=apns_config) as client:
  File "/Users/abhinavsingh/Dev/projects/.venv/lib/python3.10/site-packages/kalyke/clients/voip.py", line 24, in _init_client
    context.load_cert_chain(self._auth_key_filepath)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3895)
```
